#!/bin/bash

# This script provides instructions for setting up pfSense in Proxmox
# It cannot be fully automated as it requires Proxmox GUI interactions

echo "======================================================================="
echo "                   pfSense Setup Guide for Proxmox                     "
echo "======================================================================="
echo ""
echo "This script will guide you through the process of setting up pfSense"
echo "as a virtual router in your Proxmox environment."
echo ""
echo "Prerequisites:"
echo "  1. Download pfSense ISO from: https://www.pfsense.org/download/"
echo "  2. Upload the ISO to your Proxmox server"
echo ""
echo "Steps to set up pfSense in Proxmox:"
echo ""
echo "1. Log in to your Proxmox web interface"
echo ""
echo "2. Upload the pfSense ISO to the local storage:"
echo "   - Select your Proxmox node"
echo "   - Go to 'local' storage"
echo "   - Select 'ISO Images' tab"
echo "   - Click 'Upload'"
echo "   - Select the pfSense ISO file from your computer"
echo ""
echo "3. Create a new VM for pfSense:"
echo "   - Click 'Create VM'"
echo "   - General: Set name to 'pfsense'"
echo "   - OS: Select 'Use CD/DVD disc image file', choose the pfSense ISO"
echo "   - System: Use defaults (BIOS, standard)"
echo "   - Disks: 8-16 GB is sufficient"
echo "   - CPU: 1-2 cores is sufficient"
echo "   - Memory: 1-2 GB is sufficient"
echo "   - Network: Add at least 2 network interfaces:"
echo "     * Net0: Bridge to your external network (WAN)"
echo "     * Net1: Bridge to your internal network (LAN)"
echo "   - Confirm settings and create the VM"
echo ""
echo "4. Start the VM and follow the pfSense installation wizard:"
echo "   - Accept defaults for most options"
echo "   - Choose 'Auto (ZFS)' for file system"
echo "   - After installation completes, the system will reboot"
echo ""
echo "5. Initial pfSense configuration:"
echo "   - When prompted, do not set up VLAN now"
echo "   - Assign WAN to the first interface (usually vtnet0)"
echo "   - Assign LAN to the second interface (usually vtnet1)"
echo "   - Confirm the assignments"
echo ""
echo "6. Access the pfSense web interface:"
echo "   - Connect a device to the LAN network"
echo "   - Open a browser and navigate to http://192.168.1.1"
echo "   - Login with default credentials (admin/pfsense)"
echo "   - Follow the setup wizard"
echo ""
echo "7. Configure pfSense for network monitoring:"
echo "   - Enable SNMP under Services > SNMP"
echo "   - Set the community string to 'public' (or a secure string of your choice)"
echo "   - Update the Prometheus configuration with the pfSense IP address"
echo ""
echo "8. Update your monitoring configuration:"
echo "   - Add the pfSense IP to your snmp targets in prometheus.yml"
echo ""
echo "======================================================================="
echo "For more details, visit: https://docs.netgate.com/pfsense/en/latest/"
echo "=======================================================================" 